const CAR_DATA = [
  {year:"1968",make:"Abarth",model:"595 Esseesse",cls:"D"},
  {year:"2016",make:"Abarth",model:"695 Biposto",cls:"B"},
  {year:"1980",make:"Abarth",model:"Fiat 131",cls:"D"},
  {year:"2023",make:"Acura",model:"Integra A-Spec",cls:"C"},
  {year:"2001",make:"Acura",model:"Integra Type R",cls:"C"},
  {year:"2022",make:"Acura",model:"NSX Type S",cls:"S1"},
  {year:"2002",make:"Acura",model:"RSX Type S",cls:"C"},
  {year:"1992",make:"Alfa Romeo",model:"155 Q4",cls:"C"},
  {year:"1968",make:"Alfa Romeo",model:"33 Stradale",cls:"B"},
  {year:"2014",make:"Alfa Romeo",model:"4C",cls:"A"},
  {year:"2007",make:"Alfa Romeo",model:"8C Competizione",cls:"A"},
  {year:"2021",make:"Alfa Romeo",model:"Giulia GTAm",cls:"S1"},
  {year:"2017",make:"Alfa Romeo",model:"Giulia Quadrifoglio",cls:"A"},
  {year:"1965",make:"Alfa Romeo",model:"Giulia Sprint GTA Stradale",cls:"D"},
  {year:"1965",make:"Alfa Romeo",model:"Giulia TZ2",cls:"B"},
  {year:"1990",make:"Alfa Romeo",model:"SE 048SP",cls:"R"},
  {year:"2021",make:"Alumicraft",model:"#122 Class 1 Buggy",cls:"B"},
  {year:"2022",make:"Alumicraft",model:"#6165 Trick Truck",cls:"C"},
  {year:"2015",make:"Alumicraft",model:"Class 10 Race Car",cls:"B"},
  {year:"2554",make:"AMG Transport Dynamics",model:"M12S Warthog CST",cls:"A"},
  {year:"2019",make:"Apollo",model:"Intensa Emozione",cls:"R"},
  {year:"2013",make:"Ariel",model:"Atom 500 V8",cls:"S2"},
  {year:"2016",make:"Ariel",model:"Nomad",cls:"A"},
  {year:"2017",make:"Aston Martin",model:"DB11",cls:"A"},
  {year:"1964",make:"Aston Martin",model:"DB5",cls:"C"},
  {year:"2019",make:"Aston Martin",model:"DBS Superleggera",cls:"S1"},
  {year:"2021",make:"Aston Martin",model:"DBX",cls:"A"},
  {year:"2019",make:"Aston Martin",model:"Valhalla Concept Car",cls:"R"},
  {year:"2023",make:"Aston Martin",model:"Valkyrie",cls:"R"},
  {year:"2022",make:"Aston Martin",model:"Valkyrie AMR Pro",cls:"R"},
  {year:"2019",make:"Aston Martin",model:"Vantage",cls:"A"},
  {year:"2016",make:"Aston Martin",model:"Vulcan",cls:"S2"},
  {year:"2017",make:"Aston Martin",model:"Vulcan AMR Pro",cls:"S2"},
  {year:"1986",make:"Audi",model:"#2 Audi Sport Quattro S1",cls:"S1"},
  {year:"2023",make:"Audi",model:"R8 Coupé V10 GT RWD",cls:"S1"},
  {year:"2013",make:"Audi",model:"R8 Coupé V10 Plus 5.2 FSI Quattro",cls:"A"},
  {year:"2009",make:"Audi",model:"R8 LMS",cls:"S2"},
  {year:"2020",make:"Audi",model:"R8 V10 Performance",cls:"S1"},
  {year:"2016",make:"Audi",model:"R8 V10 Plus",cls:"S1"},
  {year:"2020",make:"Audi",model:"RS 3 Sedan",cls:"A"},
  {year:"2011",make:"Audi",model:"RS 3 Sportback",cls:"B"},
  {year:"2006",make:"Audi",model:"RS 4",cls:"B"},
  {year:"2001",make:"Audi",model:"RS 4 Avant",cls:"B"},
  {year:"2013",make:"Audi",model:"RS 4 Avant",cls:"A"},
  {year:"2018",make:"Audi",model:"RS 4 Avant",cls:"A"},
  {year:"2011",make:"Audi",model:"RS 5 Coupé",cls:"A"},
  {year:"2003",make:"Audi",model:"RS 6",cls:"B"},
  {year:"2009",make:"Audi",model:"RS 6",cls:"B"},
  {year:"2015",make:"Audi",model:"RS 6 Avant",cls:"A"},
  {year:"2021",make:"Audi",model:"RS 6 Avant",cls:"A"},
  {year:"2013",make:"Audi",model:"RS 7 Sportback",cls:"A"},
  {year:"2021",make:"Audi",model:"RS 7 Sportback",cls:"A"},
  {year:"2021",make:"Audi",model:"RS e-tron GT",cls:"A"},
  {year:"2015",make:"Audi",model:"S1",cls:"B"},
  {year:"1984",make:"Audi",model:"Sport Quattro",cls:"B"},
  {year:"2010",make:"Audi",model:"TT RS Coupé",cls:"B"},
  {year:"1965",make:"Austin-Healey",model:"3000 Mk III",cls:"D"},
  {year:"1993",make:"Autozam",model:"AZ-1",cls:"D"},
  {year:"2014",make:"BAC",model:"Mono",cls:"S1"},
  {year:"2016",make:"Bentley",model:"Bentayga",cls:"A"},
  {year:"2021",make:"Bentley",model:"Continental GT Convertible",cls:"A"},
  {year:"1973",make:"BMW",model:"2002 Turbo",cls:"C"},
  {year:"1995",make:"BMW",model:"850CSi",cls:"C"},
  {year:"2015",make:"BMW",model:"i8",cls:"A"},
  {year:"1957",make:"BMW",model:"Isetta 300 Export",cls:"D"},
  {year:"2022",make:"BMW",model:"iX xDrive50",cls:"B"},
  {year:"1981",make:"BMW",model:"M1",cls:"B"},
  {year:"2023",make:"BMW",model:"M2",cls:"A"},
  {year:"2020",make:"BMW",model:"M2 Competition Coupé",cls:"A"},
  {year:"2023",make:"BMW",model:"M2 Forza Edition",cls:"A"},
  {year:"1988",make:"BMW",model:"M3",cls:"C"},
  {year:"1997",make:"BMW",model:"M3",cls:"B"},
  {year:"2005",make:"BMW",model:"M3",cls:"B"},
  {year:"2008",make:"BMW",model:"M3",cls:"A"},
  {year:"2010",make:"BMW",model:"M3 GTS",cls:"A"},
  {year:"2021",make:"BMW",model:"M4 Competition Coupé",cls:"A"},
  {year:"2021",make:"BMW",model:"M4 Competition Coupé Welcome Pack",cls:"S1"},
  {year:"2014",make:"BMW",model:"M4 Coupé",cls:"A"},
  {year:"2016",make:"BMW",model:"M4 GTS",cls:"S1"},
  {year:"1988",make:"BMW",model:"M5",cls:"C"},
  {year:"1995",make:"BMW",model:"M5",cls:"B"},
  {year:"2003",make:"BMW",model:"M5",cls:"B"},
  {year:"2009",make:"BMW",model:"M5",cls:"B"},
  {year:"2012",make:"BMW",model:"M5",cls:"A"},
  {year:"2022",make:"BMW",model:"M5 CS",cls:"S1"},
  {year:"2020",make:"BMW",model:"M8 Competition Coupé",cls:"A"},
  {year:"2011",make:"BMW",model:"X5 M",cls:"B"},
  {year:"2024",make:"BMW",model:"X6 M Competition",cls:"A"},
  {year:"2008",make:"BMW",model:"Z4 M Coupé",cls:"B"},
  {year:"2019",make:"BMW",model:"Z4 Roadster",cls:"A"},
  {year:"1987",make:"Buick",model:"Regal GNX",cls:"C"},
  {year:"2016",make:"Cadillac",model:"ATS-V",cls:"A"},
  {year:"2022",make:"Cadillac",model:"CT4-V Blackwing",cls:"A"},
  {year:"2022",make:"Cadillac",model:"CT5-V Blackwing",cls:"S1"},
  {year:"2016",make:"Cadillac",model:"CTS-V Sedan",cls:"A"},
  {year:"2013",make:"Cadillac",model:"XTS Limousine",cls:"D"},
  {year:"2018",make:"Can-Am",model:"Maverick X RS Turbo R",cls:"B"},
  {year:"2019",make:"Casey Currie Motorsports",model:"#4402 Ultra 4 'Trophy Jeep'",cls:"A"},
  {year:"1955",make:"Chevrolet",model:"150 Utility Sedan",cls:"D"},
  {year:"1957",make:"Chevrolet",model:"Bel Air",cls:"D"},
  {year:"1969",make:"Chevrolet",model:"Camaro Super Sport Coupe",cls:"C"},
  {year:"2015",make:"Chevrolet",model:"Camaro Z/28",cls:"A"},
  {year:"1970",make:"Chevrolet",model:"Camaro Z28",cls:"C"},
  {year:"1979",make:"Chevrolet",model:"Camaro Z28",cls:"D"},
  {year:"2017",make:"Chevrolet",model:"Camaro ZL1",cls:"S1"},
  {year:"2018",make:"Chevrolet",model:"Camaro ZL1 1LE",cls:"S1"},
  {year:"1970",make:"Chevrolet",model:"Chevelle Super Sport 454",cls:"C"},
  {year:"1953",make:"Chevrolet",model:"Corvette",cls:"D"},
  {year:"1960",make:"Chevrolet",model:"Corvette",cls:"C"},
  {year:"2024",make:"Chevrolet",model:"Corvette E-Ray",cls:"S1"},
  {year:"1967",make:"Chevrolet",model:"Corvette Stingray 427",cls:"B"},
  {year:"2020",make:"Chevrolet",model:"Corvette Stingray Coupe",cls:"A"},
  {year:"2002",make:"Chevrolet",model:"Corvette Z06",cls:"A"},
  {year:"2015",make:"Chevrolet",model:"Corvette Z06",cls:"S1"},
  {year:"2023",make:"Chevrolet",model:"Corvette Z06",cls:"S1"},
  {year:"1970",make:"Chevrolet",model:"Corvette ZR-1",cls:"C"},
  {year:"1995",make:"Chevrolet",model:"Corvette ZR-1",cls:"B"},
  {year:"2009",make:"Chevrolet",model:"Corvette ZR1",cls:"S1"},
  {year:"2019",make:"Chevrolet",model:"Corvette ZR1",cls:"S1"},
  {year:"1970",make:"Chevrolet",model:"El Camino Super Sport 454",cls:"C"},
  {year:"1996",make:"Chevrolet",model:"Impala Super Sport",cls:"C"},
  {year:"1964",make:"Chevrolet",model:"Impala Super Sport 409",cls:"C"},
  {year:"1972",make:"Chevrolet",model:"K-10 Custom",cls:"D"},
  {year:"1988",make:"Chevrolet",model:"Monte Carlo Super Sport",cls:"D"},
  {year:"1969",make:"Chevrolet",model:"Nova Super Sport 396",cls:"C"},
  {year:"2020",make:"Chevrolet",model:"Silverado LT Trail Boss",cls:"C"},
  {year:"1970",make:"Datsun",model:"510",cls:"D"},
  {year:"1972",make:"Datsun",model:"#269 Attacking the Clock Racing 240Z 'All Carbon Hill Climb Beast'",cls:"R"},
  {year:"1969",make:"Datsun",model:"2000 Roadster",cls:"D"},
  {year:"2018",make:"DeBerti",model:"Chevrolet Silverado 1500 Drift Truck",cls:"S1"},
  {year:"2019",make:"DeBerti",model:"Ford Super Duty F-250 Lariat 'Transformer'",cls:"B"},
  {year:"2013",make:"DeBerti",model:"Jeep Wrangler Unlimited",cls:"A"},
  {year:"2019",make:"DeBerti",model:"Toyota Tacoma TRD ‘The Performance Truck’",cls:"S1"},
  {year:"1982",make:"DeLorean",model:"DMC-12",cls:"D"},
  {year:"1970",make:"Dodge",model:"Challenger R/T",cls:"C"},
  {year:"2018",make:"Dodge",model:"Challenger SRT Demon",cls:"A"},
  {year:"2015",make:"Dodge",model:"Challenger SRT Hellcat",cls:"A"},
  {year:"2022",make:"Dodge",model:"Challenger SRT Super Stock",cls:"A"},
  {year:"1969",make:"Dodge",model:"Charger Daytona HEMI",cls:"C"},
  {year:"1969",make:"Dodge",model:"Charger R/T",cls:"C"},
  {year:"2015",make:"Dodge",model:"Charger SRT Hellcat",cls:"A"},
  {year:"1970",make:"Dodge",model:"Coronet Super Bee",cls:"C"},
  {year:"1968",make:"Dodge",model:"Dart HEMI Super Stock",cls:"B"},
  {year:"2021",make:"Dodge",model:"Durango SRT Hellcat",cls:"A"},
  {year:"2006",make:"Dodge",model:"Ram SRT-10",cls:"B"},
  {year:"2016",make:"Dodge",model:"Viper ACR",cls:"S1"},
  {year:"1999",make:"Dodge",model:"Viper GTS ACR",cls:"B"},
  {year:"1999",make:"Dodge",model:"Viper GTS ACR Forza Edition",cls:"A"},
  {year:"2008",make:"Dodge",model:"Viper SRT-10 ACR",cls:"S1"},
  {year:"1967",make:"Ferrari",model:"#24 Ferrari Spa 330 P4",cls:"A"},
  {year:"1962",make:"Ferrari",model:"250 GT Berlinetta Lusso",cls:"C"},
  {year:"1962",make:"Ferrari",model:"250 GTO",cls:"C"},
  {year:"1967",make:"Ferrari",model:"275 GTB4 Spider",cls:"C"},
  {year:"1984",make:"Ferrari",model:"288 GTO",cls:"A"},
  {year:"2022",make:"Ferrari",model:"296 GTB",cls:"S2"},
  {year:"2007",make:"Ferrari",model:"430 Scuderia",cls:"S1"},
  {year:"2009",make:"Ferrari",model:"458 Italia",cls:"S1"},
  {year:"2013",make:"Ferrari",model:"458 Speciale",cls:"S1"},
  {year:"2015",make:"Ferrari",model:"488 GTB",cls:"S1"},
  {year:"2019",make:"Ferrari",model:"488 Pista",cls:"S2"},
  {year:"1970",make:"Ferrari",model:"512 S",cls:"S1"},
  {year:"1992",make:"Ferrari",model:"512 TR",cls:"A"},
  {year:"2010",make:"Ferrari",model:"599XX",cls:"S2"},
  {year:"2012",make:"Ferrari",model:"599XX Evolution",cls:"S2"},
  {year:"2017",make:"Ferrari",model:"812 Superfast",cls:"S1"},
  {year:"1969",make:"Ferrari",model:"Dino 246 GT",cls:"C"},
  {year:"2002",make:"Ferrari",model:"Enzo Ferrari",cls:"S1"},
  {year:"2015",make:"Ferrari",model:"F12tdf",cls:"S1"},
  {year:"1994",make:"Ferrari",model:"F355 Berlinetta",cls:"B"},
  {year:"1987",make:"Ferrari",model:"F40",cls:"A"},
  {year:"1989",make:"Ferrari",model:"F40 Competizione",cls:"R"},
  {year:"1995",make:"Ferrari",model:"F50",cls:"A"},
  {year:"1996",make:"Ferrari",model:"F50 GT",cls:"R"},
  {year:"2019",make:"Ferrari",model:"F8 Tributo",cls:"S2"},
  {year:"2025",make:"Ferrari",model:"F80",cls:"R"},
  {year:"2005",make:"Ferrari",model:"FXX",cls:"S2"},
  {year:"2014",make:"Ferrari",model:"FXX K",cls:"R"},
  {year:"2018",make:"Ferrari",model:"FXX-K Evo",cls:"R"},
  {year:"2018",make:"Ferrari",model:"FXX-K Evo Welcome Pack",cls:"R"},
  {year:"2017",make:"Ferrari",model:"J50",cls:"S1"},
  {year:"2017",make:"Ferrari",model:"J50 Preorder Car",cls:"S1"},
  {year:"2013",make:"Ferrari",model:"LaFerrari",cls:"S2"},
  {year:"2019",make:"Ferrari",model:"Monza SP2",cls:"S1"},
  {year:"2018",make:"Ferrari",model:"Portofino",cls:"S1"},
  {year:"2020",make:"Ferrari",model:"Roma",cls:"S1"},
  {year:"2020",make:"Ferrari",model:"SF90 Stradale",cls:"S2"},
  {year:"2014",make:"Ford",model:"#11 Rockstar F-150 Trophy Truck",cls:"A"},
  {year:"2017",make:"Ford",model:"#14 Rahal Letterman Lanigan Racing Fiesta",cls:"S1"},
  {year:"1966",make:"Ford",model:"#2 GT40 Mk II",cls:"A"},
  {year:"2020",make:"Ford",model:"#2069 Ford Performance Bronco R",cls:"C"},
  {year:"2017",make:"Ford",model:"#25 'Brocky' Ultra4 Bronco RTR",cls:"A"},
  {year:"2001",make:"Ford",model:"#4 Ford Focus RS",cls:"A"},
  {year:"1977",make:"Ford",model:"#5 Escort RS1800 Mk II",cls:"B"},
  {year:"2022",make:"Ford",model:"Bronco Raptor",cls:"C"},
  {year:"1973",make:"Ford",model:"Capri RS3100",cls:"D"},
  {year:"2010",make:"Ford",model:"Crown Victoria Police Interceptor",cls:"D"},
  {year:"1932",make:"Ford",model:"De Luxe Five-Window Coupe",cls:"D"},
  {year:"1992",make:"Ford",model:"Escort RS Cosworth",cls:"C"},
  {year:"2022",make:"Ford",model:"F-150 Lightning",cls:"C"},
  {year:"2023",make:"Ford",model:"F-150 Raptor R",cls:"B"},
  {year:"2023",make:"Ford",model:"F-150 Raptor R Welcome Pack",cls:"B"},
  {year:"2003",make:"Ford",model:"F-150 SVT Lightning",cls:"C"},
  {year:"1986",make:"Ford",model:"F-150 XLT Lariat",cls:"D"},
  {year:"1986",make:"Ford",model:"F-150 XLT Lariat Forza Edition",cls:"S2"},
  {year:"2023",make:"Ford",model:"Fiesta ST",cls:"C"},
  {year:"2003",make:"Ford",model:"Focus RS",cls:"C"},
  {year:"2009",make:"Ford",model:"Focus RS",cls:"B"},
  {year:"2017",make:"Ford",model:"Focus RS",cls:"B"},
  {year:"2022",make:"Ford",model:"Focus ST",cls:"B"},
  {year:"2014",make:"Ford",model:"FPV Limited Edition Pursuit Ute",cls:"B"},
  {year:"2005",make:"Ford",model:"GT",cls:"A"},
  {year:"2017",make:"Ford",model:"GT",cls:"S1"},
  {year:"2017",make:"Ford",model:"M-Sport Fiesta RS",cls:"S1"},
  {year:"1969",make:"Ford",model:"Mustang Boss 302",cls:"C"},
  {year:"2024",make:"Ford",model:"Mustang Dark Horse",cls:"A"},
  {year:"2024",make:"Ford",model:"Mustang GT",cls:"A"},
  {year:"1968",make:"Ford",model:"Mustang GT 2+2 Fastback",cls:"D"},
  {year:"1968",make:"Ford",model:"Mustang GT 2+2 Fastback Forza Edition",cls:"A"},
  {year:"1965",make:"Ford",model:"Mustang GT Coupe",cls:"D"},
  {year:"2018",make:"Ford",model:"Mustang RTR Spec 5",cls:"A"},
  {year:"2016",make:"Ford",model:"Mustang Shelby GT350R",cls:"S1"},
  {year:"2013",make:"Ford",model:"Mustang Shelby GT500",cls:"A"},
  {year:"2020",make:"Ford",model:"Mustang Shelby GT500",cls:"S1"},
  {year:"1993",make:"Ford",model:"Mustang SVT Cobra R",cls:"C"},
  {year:"2000",make:"Ford",model:"Mustang SVT Cobra R",cls:"B"},
  {year:"1999",make:"Ford",model:"Racing Puma",cls:"C"},
  {year:"2014",make:"Ford",model:"Ranger T6 Rally Raid",cls:"B"},
  {year:"1985",make:"Ford",model:"RS200 Evolution",cls:"S1"},
  {year:"1987",make:"Ford",model:"Sierra Cosworth RS500",cls:"C"},
  {year:"2020",make:"Ford",model:"Super Duty F-450 DRW PLATINUM",cls:"D"},
  {year:"2020",make:"Ford",model:"Super Duty F-450 DRW PLATINUM Forza Edition",cls:"A"},
  {year:"1994",make:"Ford",model:"Supervan 3",cls:"S1"},
  {year:"2022",make:"Ford",model:"Supervan 4",cls:"R"},
  {year:"2011",make:"Ford",model:"Transit SuperSportVan",cls:"D"},
  {year:"1973",make:"Ford",model:"XB Falcon GT",cls:"C"},
  {year:"2007",make:"Formula Drift",model:"#117 599 GTB Fiorano",cls:"S1"},
  {year:"2015",make:"Formula Drift",model:"#13 Ford Mustang",cls:"S1"},
  {year:"2020",make:"Formula Drift",model:"#151 Toyota GR Supra",cls:"S1"},
  {year:"1995",make:"Formula Drift",model:"#34 Toyota Supra MkIV",cls:"S1"},
  {year:"2019",make:"Formula Drift",model:"#411 Toyota Corolla Hatchback",cls:"S1"},
  {year:"2006",make:"Formula Drift",model:"#43 Dodge Viper SRT-10 ACR",cls:"S1"},
  {year:"2016",make:"Formula Drift",model:"#530 HSV Maloo GEN-F",cls:"S1"},
  {year:"2023",make:"Formula Drift",model:"#64 Forsberg Racing Nissan Z",cls:"S1"},
  {year:"2013",make:"Formula Drift",model:"#777 Chevrolet Corvette",cls:"S1"},
  {year:"1997",make:"Formula Drift",model:"#777 Nissan 240SX",cls:"S1"},
  {year:"2020",make:"Formula Drift",model:"#91 BMW M2",cls:"S1"},
  {year:"1989",make:"Formula Drift",model:"#98 BMW 325i",cls:"S1"},
  {year:"2009",make:"Formula Drift",model:"#99 Mazda RX-8",cls:"S1"},
  {year:"2018",make:"Funco Motorsports",model:"F9",cls:"S1"},
  {year:"2022",make:"GMC",model:"HUMMER EV Pickup",cls:"A"},
  {year:"1970",make:"GMC",model:"Jimmy",cls:"C"},
  {year:"1991",make:"GMC",model:"Syclone",cls:"C"},
  {year:"1992",make:"GMC",model:"Typhoon",cls:"C"},
  {year:"2020",make:"Gordon Murray Automotive",model:"T.50",cls:"S2"},
  {year:"2025",make:"GR",model:"GT Prototype",cls:"S1"},
  {year:"2019",make:"Hennessey",model:"Ford F-150 VelociRaptor 6x6",cls:"B"},
  {year:"2021",make:"Hennessey",model:"Venom F5",cls:"S2"},
  {year:"2012",make:"Hennessey",model:"Venom GT",cls:"S2"},
  {year:"1977",make:"Holden",model:"Torana A9X",cls:"C"},
  {year:"1990",make:"Honda",model:"#19 101 Motorsport CRX WTAC",cls:"S2"},
  {year:"1992",make:"Honda",model:"#21 Hardrace/JDMYard Civic WTAC",cls:"R"},
  {year:"2001",make:"Honda",model:"#33 Integra WTAC",cls:"S2"},
  {year:"2004",make:"Honda",model:"#52 Evasive Motorsports S2000 WTAC",cls:"S2"},
  {year:"1994",make:"Honda",model:"Acty",cls:"D"},
  {year:"1991",make:"Honda",model:"Beat",cls:"D"},
  {year:"1984",make:"Honda",model:"City E II",cls:"D"},
  {year:"1984",make:"Honda",model:"Civic CRX Mugen",cls:"D"},
  {year:"1974",make:"Honda",model:"Civic RS",cls:"D"},
  {year:"1986",make:"Honda",model:"Civic Si",cls:"D"},
  {year:"1997",make:"Honda",model:"Civic Type R",cls:"C"},
  {year:"2004",make:"Honda",model:"Civic Type R",cls:"C"},
  {year:"2007",make:"Honda",model:"Civic Type R",cls:"C"},
  {year:"2015",make:"Honda",model:"Civic Type R",cls:"B"},
  {year:"2018",make:"Honda",model:"Civic Type R",cls:"A"},
  {year:"2023",make:"Honda",model:"Civic Type R",cls:"A"},
  {year:"2008",make:"Honda",model:"Civic Type R (FD2)",cls:"B"},
  {year:"1991",make:"Honda",model:"CR-X SiR",cls:"C"},
  {year:"2022",make:"Honda",model:"e",cls:"D"},
  {year:"1992",make:"Honda",model:"NSX-R",cls:"B"},
  {year:"2005",make:"Honda",model:"NSX-R",cls:"B"},
  {year:"2005",make:"Honda",model:"NSX-R GT",cls:"A"},
  {year:"1994",make:"Honda",model:"Prelude Si",cls:"C"},
  {year:"2015",make:"Honda",model:"Ridgeline Baja Trophy Truck",cls:"B"},
  {year:"2003",make:"Honda",model:"S2000",cls:"B"},
  {year:"1970",make:"Honda",model:"S800",cls:"D"},
  {year:"2014",make:"HSV",model:"GEN-F GTS",cls:"A"},
  {year:"2014",make:"HSV",model:"Limited Edition GEN-F GTS Maloo",cls:"A"},
  {year:"2021",make:"Hyundai",model:"i20 N",cls:"B"},
  {year:"2020",make:"Hyundai",model:"i30 N",cls:"B"},
  {year:"2023",make:"Hyundai",model:"IONIQ 5 N",cls:"A"},
  {year:"2022",make:"Hyundai",model:"N Vision 74",cls:"A"},
  {year:"2019",make:"Hyundai",model:"Veloster N",cls:"B"},
  {year:"2010",make:"Jaguar",model:"C-X75",cls:"S2"},
  {year:"1956",make:"Jaguar",model:"D-Type",cls:"B"},
  {year:"1961",make:"Jaguar",model:"E-type",cls:"C"},
  {year:"1964",make:"Jaguar",model:"Lightweight E-Type",cls:"B"},
  {year:"1991",make:"Jaguar",model:"Sport XJR-15",cls:"S1"},
  {year:"1993",make:"Jaguar",model:"XJ220",cls:"A"},
  {year:"1993",make:"Jaguar",model:"XJ220S TWR",cls:"S1"},
  {year:"2018",make:"Jeep",model:"Grand Cherokee Trackhawk",cls:"A"},
  {year:"2020",make:"Jeep",model:"JT",cls:"D"},
  {year:"2016",make:"Jeep",model:"Trailcat",cls:"A"},
  {year:"2012",make:"Jeep",model:"Wrangler Rubicon",cls:"D"},
  {year:"2020",make:"Jimco",model:"#179 Hammerhead Class 1",cls:"A"},
  {year:"2019",make:"Jimco",model:"#240 Fastball Racing Class 6100 Spec Trophy Truck",cls:"B"},
  {year:"2011",make:"Koenigsegg",model:"Agera",cls:"S2"},
  {year:"2017",make:"Koenigsegg",model:"Agera RS",cls:"S2"},
  {year:"2008",make:"Koenigsegg",model:"CCGT",cls:"S2"},
  {year:"2024",make:"Koenigsegg",model:"Gemera",cls:"S2"},
  {year:"2020",make:"Koenigsegg",model:"Jesko",cls:"S2"},
  {year:"2015",make:"Koenigsegg",model:"One:1",cls:"S2"},
  {year:"2016",make:"Koenigsegg",model:"Regera",cls:"S2"},
  {year:"2018",make:"KTM",model:"X-Bow GT4",cls:"S1"},
  {year:"2022",make:"Lamborghini",model:"Aventador LP 780-4 Ultimae",cls:"S1"},
  {year:"2012",make:"Lamborghini",model:"Aventador LP700-4",cls:"S1"},
  {year:"2018",make:"Lamborghini",model:"Aventador SVJ",cls:"S1"},
  {year:"2016",make:"Lamborghini",model:"Centenario LP 770-4",cls:"S1"},
  {year:"1988",make:"Lamborghini",model:"Countach LP5000 QV",cls:"A"},
  {year:"2021",make:"Lamborghini",model:"Countach LPI 800-4",cls:"S1"},
  {year:"1999",make:"Lamborghini",model:"Diablo GTR",cls:"S2"},
  {year:"1997",make:"Lamborghini",model:"Diablo SV",cls:"A"},
  {year:"2020",make:"Lamborghini",model:"Essenza SCV12",cls:"R"},
  {year:"2012",make:"Lamborghini",model:"Gallardo LP570-4 Spyder Performante",cls:"A"},
  {year:"2020",make:"Lamborghini",model:"Huracán EVO",cls:"S1"},
  {year:"2014",make:"Lamborghini",model:"Huracán LP 610-4",cls:"S1"},
  {year:"2022",make:"Lamborghini",model:"Huracán Sterrato",cls:"S1"},
  {year:"2020",make:"Lamborghini",model:"Huracán STO",cls:"S1"},
  {year:"2022",make:"Lamborghini",model:"Huracán Tecnica",cls:"S1"},
  {year:"1967",make:"Lamborghini",model:"Miura P400",cls:"B"},
  {year:"2010",make:"Lamborghini",model:"Murciélago LP 670-4 SV",cls:"S1"},
  {year:"2024",make:"Lamborghini",model:"Revuelto",cls:"S2"},
  {year:"2011",make:"Lamborghini",model:"Sesto Elemento",cls:"S2"},
  {year:"2020",make:"Lamborghini",model:"Sián Roadster",cls:"S1"},
  {year:"2019",make:"Lamborghini",model:"Urus",cls:"A"},
  {year:"2013",make:"Lamborghini",model:"Veneno",cls:"S2"},
  {year:"1992",make:"Lancia",model:"Delta HF Integrale EVO",cls:"C"},
  {year:"1986",make:"Lancia",model:"Delta S4",cls:"B"},
  {year:"1974",make:"Lancia",model:"Stratos HF Stradale",cls:"C"},
  {year:"2020",make:"Land Rover",model:"Defender 110 X",cls:"C"},
  {year:"2015",make:"Land Rover",model:"Range Rover Sport SVR",cls:"A"},
  {year:"2021",make:"Lexus",model:"LC 500",cls:"B"},
  {year:"2010",make:"Lexus",model:"LFA",cls:"A"},
  {year:"2010",make:"Lexus",model:"LFA Forza Edition",cls:"S2"},
  {year:"2015",make:"Lexus",model:"RC F",cls:"A"},
  {year:"1962",make:"Lincoln",model:"Continental",cls:"D"},
  {year:"1997",make:"Lotus",model:"Elise GT1",cls:"S1"},
  {year:"1999",make:"Lotus",model:"Elise Series 1 Sport 190",cls:"B"},
  {year:"2023",make:"Lotus",model:"Emira",cls:"A"},
  {year:"2020",make:"Lotus",model:"Evija",cls:"R"},
  {year:"2020",make:"Lotus",model:"Evija Forza Edition",cls:"S2"},
  {year:"2018",make:"Lotus",model:"Exige Cup 430",cls:"S1"},
  {year:"2018",make:"Lotus",model:"Scura Motorsports Exige WTAC",cls:"R"},
  {year:"2024",make:"Lucid",model:"Air Sapphire",cls:"S2"},
  {year:"1997",make:"Maserati",model:"Ghibli Cup",cls:"B"},
  {year:"2004",make:"Maserati",model:"MC12",cls:"S1"},
  {year:"2008",make:"Maserati",model:"MC12 Versione Corsa",cls:"R"},
  {year:"2022",make:"Maserati",model:"MC20",cls:"S1"},
  {year:"1974",make:"Mazda",model:"#123 Mad Mike 808 Wagon 'FURSTY'",cls:"S1"},
  {year:"1991",make:"Mazda",model:"#55 Mazda 787B",cls:"R"},
  {year:"1972",make:"Mazda",model:"Cosmo 110S Series II",cls:"D"},
  {year:"2008",make:"Mazda",model:"Furai",cls:"R"},
  {year:"2010",make:"Mazda",model:"Mazdaspeed 3",cls:"B"},
  {year:"2005",make:"Mazda",model:"Mazdaspeed MX-5",cls:"C"},
  {year:"2013",make:"Mazda",model:"MX-5",cls:"C"},
  {year:"2016",make:"Mazda",model:"MX-5",cls:"C"},
  {year:"2017",make:"Mazda",model:"MX-5 Cup",cls:"B"},
  {year:"1994",make:"Mazda",model:"MX-5 Miata",cls:"D"},
  {year:"1994",make:"Mazda",model:"MX-5 Miata Forza Edition",cls:"S2"},
  {year:"2022",make:"Mazda",model:"MX-5 Miata RF",cls:"B"},
  {year:"1973",make:"Mazda",model:"RX-3",cls:"D"},
  {year:"1973",make:"Mazda",model:"RX-3 Forza Edition",cls:"B"},
  {year:"1985",make:"Mazda",model:"RX-7 GSL-SE",cls:"D"},
  {year:"1992",make:"Mazda",model:"RX-7 Type R",cls:"B"},
  {year:"2011",make:"Mazda",model:"RX-8 R3",cls:"B"},
  {year:"1990",make:"Mazda",model:"Savanna RX-7",cls:"C"},
  {year:"2011",make:"McLaren",model:"12C Coupé",cls:"S1"},
  {year:"2015",make:"McLaren",model:"570S Coupé",cls:"S1"},
  {year:"2018",make:"McLaren",model:"600LT Coupé",cls:"S1"},
  {year:"2021",make:"McLaren",model:"620R",cls:"S1"},
  {year:"2014",make:"McLaren",model:"650S Spider",cls:"S1"},
  {year:"2021",make:"McLaren",model:"765LT Coupé",cls:"S2"},
  {year:"2023",make:"McLaren",model:"Artura",cls:"S1"},
  {year:"1993",make:"McLaren",model:"F1",cls:"S1"},
  {year:"1997",make:"McLaren",model:"F1 GT",cls:"S1"},
  {year:"2013",make:"McLaren",model:"P1",cls:"S2"},
  {year:"2021",make:"McLaren",model:"Sabre",cls:"S1"},
  {year:"2019",make:"McLaren",model:"Speedtail",cls:"S2"},
  {year:"2016",make:"Mercedes-AMG",model:"C 63 S Coupé",cls:"A"},
  {year:"2018",make:"Mercedes-AMG",model:"E 63 S",cls:"A"},
  {year:"2018",make:"Mercedes-AMG",model:"GT 4-Door Coupé",cls:"A"},
  {year:"2020",make:"Mercedes-AMG",model:"GT Black Series",cls:"S1"},
  {year:"2020",make:"Mercedes-AMG",model:"GT Black Series Welcome Pack",cls:"S2"},
  {year:"2017",make:"Mercedes-AMG",model:"GT R",cls:"S1"},
  {year:"2015",make:"Mercedes-AMG",model:"GT S",cls:"A"},
  {year:"2021",make:"Mercedes-AMG",model:"Mercedes-AMG ONE",cls:"S2"},
  {year:"2021",make:"Mercedes-AMG",model:"SL 63",cls:"A"},
  {year:"2020",make:"Mercedes-AMG",model:"SLC 43 Final Edition",cls:"A"},
  {year:"1990",make:"Mercedes-Benz",model:"190 E 2.5-16 Evolution II",cls:"C"},
  {year:"1990",make:"Mercedes-Benz",model:"190 E 2.5-16 Evolution II Forza Edition",cls:"A"},
  {year:"1954",make:"Mercedes-Benz",model:"300 SL Coupé",cls:"D"},
  {year:"1955",make:"Mercedes-Benz",model:"300 SLR",cls:"B"},
  {year:"2013",make:"Mercedes-Benz",model:"A 45 AMG",cls:"B"},
  {year:"1998",make:"Mercedes-Benz",model:"AMG CLK GTR",cls:"S1"},
  {year:"1987",make:"Mercedes-Benz",model:"AMG Hammer Coupe",cls:"B"},
  {year:"2012",make:"Mercedes-Benz",model:"C 63 AMG Coupé Black Series",cls:"A"},
  {year:"2014",make:"Mercedes-Benz",model:"G 63 AMG 6x6",cls:"C"},
  {year:"2013",make:"Mercedes-Benz",model:"G 65 AMG",cls:"B"},
  {year:"2009",make:"Mercedes-Benz",model:"SL 65 AMG Black Series",cls:"A"},
  {year:"2014",make:"Mercedes-Benz",model:"Unimog U5023",cls:"D"},
  {year:"2018",make:"Mercedes-Benz",model:"X-Class",cls:"D"},
  {year:"1971",make:"Meyers",model:"Manx",cls:"D"},
  {year:"2023",make:"Meyers",model:"Manx 2.0",cls:"B"},
  {year:"1986",make:"MG",model:"Metro 6R4",cls:"A"},
  {year:"1965",make:"MINI",model:"Cooper S",cls:"D"},
  {year:"2012",make:"MINI",model:"John Cooper Works GP",cls:"B"},
  {year:"2021",make:"MINI",model:"John Cooper Works GP",cls:"B"},
  {year:"2013",make:"MINI",model:"X-Raid All4 Racing Countryman",cls:"B"},
  {year:"2018",make:"MINI",model:"X-Raid John Cooper Works Buggy",cls:"B"},
  {year:"2005",make:"Mitsubishi",model:"#1 Sierra Sierra Enterprises Lancer Evolution Time Attack",cls:"R"},
  {year:"1990",make:"Mitsubishi",model:"#269 Attacking the Clock Racing Minicab Time Attack",cls:"D"},
  {year:"1995",make:"Mitsubishi",model:"Eclipse GSX",cls:"C"},
  {year:"1992",make:"Mitsubishi",model:"Galant VR-4",cls:"C"},
  {year:"1997",make:"Mitsubishi",model:"GTO",cls:"C"},
  {year:"1995",make:"Mitsubishi",model:"Lancer Evolution III GSR",cls:"B"},
  {year:"2006",make:"Mitsubishi",model:"Lancer Evolution IX MR",cls:"B"},
  {year:"2001",make:"Mitsubishi",model:"Lancer Evolution VI GSR TM Edition",cls:"B"},
  {year:"2004",make:"Mitsubishi",model:"Lancer Evolution VIII MR",cls:"B"},
  {year:"2004",make:"Mitsubishi",model:"Lancer Evolution VIII MR Welcome Pack",cls:"A"},
  {year:"2008",make:"Mitsubishi",model:"Lancer Evolution X GSR",cls:"B"},
  {year:"1997",make:"Mitsubishi",model:"Montero Evolution",cls:"D"},
  {year:"1995",make:"Mitsubishi",model:"Montero Exceed 2800 TD",cls:"D"},
  {year:"1983",make:"Nissan",model:"#11 Tomica Skyline Turbo Super Silhouette",cls:"S2"},
  {year:"1990",make:"Nissan",model:"#12 Skyline GT-R (BNR32 Gr.A) JTC",cls:"S2"},
  {year:"1998",make:"Nissan",model:"#23 Pennzoil NISMO Skyline GT-R",cls:"S2"},
  {year:"1993",make:"Nissan",model:"#32 Skyline WTAC 'Xtreme GTR'",cls:"R"},
  {year:"2000",make:"Nissan",model:"#36 Dream Project S15 Silvia WTAC",cls:"R"},
  {year:"1993",make:"Nissan",model:"240SX",cls:"D"},
  {year:"2010",make:"Nissan",model:"370Z",cls:"B"},
  {year:"2019",make:"Nissan",model:"370Z Nismo",cls:"A"},
  {year:"1987",make:"Nissan",model:"Be-1",cls:"D"},
  {year:"2003",make:"Nissan",model:"Fairlady Z",cls:"B"},
  {year:"1969",make:"Nissan",model:"Fairlady Z 432",cls:"D"},
  {year:"1994",make:"Nissan",model:"Fairlady Z Version S Twin Turbo",cls:"C"},
  {year:"1991",make:"Nissan",model:"Figaro",cls:"D"},
  {year:"1995",make:"Nissan",model:"Gloria Gran Turismo",cls:"C"},
  {year:"2017",make:"Nissan",model:"GT-R (R35)",cls:"S1"},
  {year:"2012",make:"Nissan",model:"GT-R Black Edition (R35)",cls:"S1"},
  {year:"2012",make:"Nissan",model:"GT-R Black Edition (R35) Forza Edition",cls:"S2"},
  {year:"2024",make:"Nissan",model:"GT-R Nismo",cls:"S1"},
  {year:"2020",make:"Nissan",model:"GT-R NISMO (R35)",cls:"S1"},
  {year:"1995",make:"Nissan",model:"NISMO GT-R LM",cls:"B"},
  {year:"1989",make:"Nissan",model:"PAO",cls:"D"},
  {year:"1990",make:"Nissan",model:"Pulsar GTI-R",cls:"C"},
  {year:"1998",make:"Nissan",model:"R390 (GT1)",cls:"S1"},
  {year:"1989",make:"Nissan",model:"S-Cargo",cls:"D"},
  {year:"1989",make:"Nissan",model:"S-Cargo Forza Edition",cls:"S1"},
  {year:"1985",make:"Nissan",model:"Safari Turbo",cls:"D"},
  {year:"1989",make:"Nissan",model:"Silvia K's",cls:"C"},
  {year:"1994",make:"Nissan",model:"Silvia K's",cls:"C"},
  {year:"1998",make:"Nissan",model:"Silvia K's Aero",cls:"C"},
  {year:"2002",make:"Nissan",model:"Silvia Spec-R",cls:"B"},
  {year:"1971",make:"Nissan",model:"Skyline 2000GT-R",cls:"D"},
  {year:"1992",make:"Nissan",model:"Skyline GT-R",cls:"B"},
  {year:"1998",make:"Nissan",model:"Skyline GT-R 40th Anniversary",cls:"B"},
  {year:"2000",make:"Nissan",model:"Skyline GT-R V Spec II",cls:"B"},
  {year:"1997",make:"Nissan",model:"Skyline GT-R V-Spec",cls:"B"},
  {year:"1987",make:"Nissan",model:"Skyline GTS-R",cls:"C"},
  {year:"1973",make:"Nissan",model:"Skyline H/T 2000GT-R",cls:"C"},
  {year:"1997",make:"Nissan",model:"Stagea RS Four V",cls:"C"},
  {year:"2024",make:"Nissan",model:"Z NISMO",cls:"A"},
  {year:"2010",make:"Noble",model:"M600",cls:"S1"},
  {year:"1984",make:"Opel",model:"Manta 400",cls:"B"},
  {year:"2016",make:"Pagani",model:"Huayra BC Coupe",cls:"S2"},
  {year:"2021",make:"Pagani",model:"Huayra R",cls:"R"},
  {year:"2010",make:"Pagani",model:"Zonda Cinque Roadster",cls:"S2"},
  {year:"2009",make:"Pagani",model:"Zonda R",cls:"R"},
  {year:"1962",make:"Peel",model:"P50",cls:"D"},
  {year:"1962",make:"Peel",model:"P50 Trolli Edition",cls:"D"},
  {year:"2011",make:"Penhall",model:"The Cholla",cls:"B"},
  {year:"1991",make:"Peugeot",model:"205 Rallye",cls:"D"},
  {year:"1984",make:"Peugeot",model:"205 Turbo 16",cls:"C"},
  {year:"2007",make:"Peugeot",model:"207 Super 2000",cls:"A"},
  {year:"1968",make:"Plymouth",model:"Barracuda Formula S",cls:"C"},
  {year:"1971",make:"Plymouth",model:"Cuda 426 HEMI",cls:"C"},
  {year:"1958",make:"Plymouth",model:"Fury",cls:"D"},
  {year:"2021",make:"Polaris",model:"RZR Pro XP Factory Racing Limited Edition",cls:"C"},
  {year:"2021",make:"Polaris",model:"RZR Pro XP Ultimate",cls:"C"},
  {year:"1977",make:"Pontiac",model:"Firebird Trans Am",cls:"D"},
  {year:"1987",make:"Pontiac",model:"Firebird Trans Am GTA",cls:"D"},
  {year:"1987",make:"Porsche",model:"959",cls:"A"},
  {year:"1985",make:"Porsche",model:"#185 959 Prodrive Rally Raid",cls:"A"},
  {year:"1970",make:"Porsche",model:"#3 917 LH",cls:"S1"},
  {year:"1970",make:"Porsche",model:"#3 917 LH Forza Edition",cls:"R"},
  {year:"2019",make:"Porsche",model:"#70 Porsche Motorsport 935",cls:"S2"},
  {year:"2022",make:"Porsche",model:"718 Cayman GT4 RS",cls:"S1"},
  {year:"2018",make:"Porsche",model:"718 Cayman GTS",cls:"A"},
  {year:"1973",make:"Porsche",model:"911 Carrera RS",cls:"C"},
  {year:"2019",make:"Porsche",model:"911 Carrera S",cls:"S1"},
  {year:"1997",make:"Porsche",model:"911 GT1 Strassenversion",cls:"S1"},
  {year:"1995",make:"Porsche",model:"911 GT2",cls:"A"},
  {year:"2018",make:"Porsche",model:"911 GT2 RS",cls:"S2"},
  {year:"2004",make:"Porsche",model:"911 GT3",cls:"A"},
  {year:"2021",make:"Porsche",model:"911 GT3",cls:"S1"},
  {year:"2019",make:"Porsche",model:"911 GT3 RS",cls:"S1"},
  {year:"2023",make:"Porsche",model:"911 GT3 RS",cls:"S1"},
  {year:"2012",make:"Porsche",model:"911 GT3 RS 4.0",cls:"S1"},
  {year:"2023",make:"Porsche",model:"911 Rallye",cls:"A"},
  {year:"1982",make:"Porsche",model:"911 Turbo 3.3",cls:"B"},
  {year:"2023",make:"Porsche",model:"911 Turbo S",cls:"S1"},
  {year:"1993",make:"Porsche",model:"911 Turbo S Leichtbau",cls:"A"},
  {year:"2014",make:"Porsche",model:"918 Spyder",cls:"S2"},
  {year:"1993",make:"Porsche",model:"928 GTS",cls:"B"},
  {year:"1989",make:"Porsche",model:"944 Turbo",cls:"B"},
  {year:"1993",make:"Porsche",model:"968 Turbo S",cls:"B"},
  {year:"2003",make:"Porsche",model:"Carrera GT",cls:"S1"},
  {year:"2018",make:"Porsche",model:"Cayenne Turbo",cls:"A"},
  {year:"2005",make:"Porsche",model:"Cayman GT3 WTAC",cls:"S2"},
  {year:"2018",make:"Porsche",model:"Macan LPR Rally Raid",cls:"B"},
  {year:"2021",make:"Porsche",model:"Mission R",cls:"S2"},
  {year:"2020",make:"Porsche",model:"Taycan Turbo S",cls:"S1"},
  {year:"2015",make:"Radical",model:"RXC Turbo",cls:"S2"},
  {year:"2024",make:"Ram",model:"1500 TRX",cls:"B"},
  {year:"1972",make:"Reliant",model:"Supervan III",cls:"D"},
  {year:"1980",make:"Renault",model:"5 Turbo",cls:"C"},
  {year:"1967",make:"Renault",model:"8 Gordini",cls:"D"},
  {year:"1993",make:"Renault",model:"Clio Williams",cls:"D"},
  {year:"2018",make:"Renault",model:"Megane R.S.",cls:"B"},
  {year:"2008",make:"Renault",model:"Mégane R26.R",cls:"B"},
  {year:"2010",make:"Renault",model:"Megane RS 250",cls:"B"},
  {year:"2021",make:"Rimac",model:"Nevera",cls:"R"},
  {year:"2022",make:"Rivian",model:"R1T",cls:"A"},
  {year:"2016",make:"RJ Anderson",model:"#37 Polaris RZR Pro 2 Truck",cls:"A"},
  {year:"2021",make:"RJ Anderson",model:"#37 Polaris RZR Pro 4 Truck",cls:"A"},
  {year:"2017",make:"Saleen",model:"S7 LM",cls:"S2"},
  {year:"1993",make:"Schuppan",model:"962CR",cls:"S1"},
  {year:"1965",make:"Shelby",model:"Cobra 427 S/C",cls:"B"},
  {year:"1965",make:"Shelby",model:"Cobra Daytona Coupe",cls:"B"},
  {year:"2020",make:"SIERRA Cars",model:"#23 Yokohama ALPHA",cls:"R"},
  {year:"2021",make:"SIERRA Cars",model:"700R",cls:"D"},
  {year:"2021",make:"SIERRA Cars",model:"RX3",cls:"A"},
  {year:"2013",make:"SRT",model:"Viper GTS",cls:"S1"},
  {year:"1980",make:"Subaru",model:"BRAT GL",cls:"D"},
  {year:"2013",make:"Subaru",model:"BRZ",cls:"C"},
  {year:"2022",make:"Subaru",model:"BRZ",cls:"B"},
  {year:"2022",make:"Subaru",model:"BRZ Forza Edition",cls:"A"},
  {year:"1998",make:"Subaru",model:"Impreza 22B-STi Version",cls:"B"},
  {year:"2004",make:"Subaru",model:"Impreza WRX STI",cls:"B"},
  {year:"2005",make:"Subaru",model:"Impreza WRX STI",cls:"B"},
  {year:"2008",make:"Subaru",model:"Impreza WRX STI",cls:"B"},
  {year:"2005",make:"Subaru",model:"Legacy B4 2.0 GT",cls:"B"},
  {year:"1990",make:"Subaru",model:"Legacy RS",cls:"C"},
  {year:"2019",make:"Subaru",model:"STI S209",cls:"B"},
  {year:"1996",make:"Subaru",model:"SVX",cls:"C"},
  {year:"1994",make:"Subaru",model:"Vivio RX-R",cls:"D"},
  {year:"1994",make:"Subaru",model:"Vivio RX-R Forza Edition",cls:"S2"},
  {year:"2022",make:"Subaru",model:"WRX",cls:"B"},
  {year:"2011",make:"Subaru",model:"WRX STI",cls:"B"},
  {year:"2015",make:"Subaru",model:"WRX STI",cls:"B"},
  {year:"2018",make:"Subaru",model:"WRX STI ARX Supercar",cls:"S1"},
  {year:"2013",make:"Toyota",model:"86",cls:"C"},
  {year:"1993",make:"Toyota",model:"#1 T100 Baja Truck",cls:"B"},
  {year:"1969",make:"Toyota",model:"2000GT",cls:"D"},
  {year:"2019",make:"Toyota",model:"4Runner TRD Pro",cls:"C"},
  {year:"2013",make:"Toyota",model:"86 Stories",cls:"A"},
  {year:"1999",make:"Toyota",model:"Altezza RS200 Z Edition",cls:"C"},
  {year:"2023",make:"Toyota",model:"Camry TRD",cls:"B"},
  {year:"1992",make:"Toyota",model:"Celica GT-Four RC ST185",cls:"C"},
  {year:"1994",make:"Toyota",model:"Celica GT-Four ST205",cls:"C"},
  {year:"2003",make:"Toyota",model:"Celica Sport Specialty II",cls:"C"},
  {year:"1997",make:"Toyota",model:"Chaser 2.5 Tourer V",cls:"B"},
  {year:"1991",make:"Toyota",model:"Chaser GT Twin Turbo",cls:"C"},
  {year:"1974",make:"Toyota",model:"Corolla SR5",cls:"D"},
  {year:"2005",make:"Toyota",model:"Crown Super Deluxe Taxi",cls:"D"},
  {year:"1979",make:"Toyota",model:"FJ40",cls:"D"},
  {year:"2023",make:"Toyota",model:"GR Corolla",cls:"B"},
  {year:"2020",make:"Toyota",model:"GR Supra",cls:"A"},
  {year:"2021",make:"Toyota",model:"GR Yaris",cls:"B"},
  {year:"2022",make:"Toyota",model:"GR86",cls:"B"},
  {year:"1995",make:"Toyota",model:"J&J Motorsport Supra WTAC",cls:"S2"},
  {year:"2017",make:"Toyota",model:"JPN Taxi",cls:"D"},
  {year:"2025",make:"Toyota",model:"Land Cruiser",cls:"C"},
  {year:"2016",make:"Toyota",model:"Land Cruiser Arctic Trucks AT37",cls:"D"},
  {year:"1995",make:"Toyota",model:"MR2 GT",cls:"B"},
  {year:"1989",make:"Toyota",model:"MR2 SC",cls:"D"},
  {year:"1991",make:"Toyota",model:"Sera",cls:"D"},
  {year:"1997",make:"Toyota",model:"Soarer 2.5 GT-T",cls:"C"},
  {year:"1965",make:"Toyota",model:"Sports 800",cls:"D"},
  {year:"1965",make:"Toyota",model:"Sports 800 Fanta Edition",cls:"D"},
  {year:"1985",make:"Toyota",model:"Sprinter Trueno GT Apex",cls:"D"},
  {year:"1985",make:"Toyota",model:"Sprinter Trueno GT Apex Forza Edition",cls:"B"},
  {year:"1996",make:"Toyota",model:"Starlet Glanza V",cls:"C"},
  {year:"1992",make:"Toyota",model:"Supra 2.0 GT",cls:"C"},
  {year:"1998",make:"Toyota",model:"Supra RZ",cls:"B"},
  {year:"2019",make:"Toyota",model:"Tacoma TRD Pro",cls:"C"},
  {year:"2019",make:"Toyota",model:"Tacoma TRD Pro Forza Edition",cls:"R"},
  {year:"1998",make:"TVR",model:"Cerbera Speed 12",cls:"S1"},
  {year:"2018",make:"TVR",model:"Griffith",cls:"S1"},
  {year:"2005",make:"TVR",model:"Sagaris",cls:"A"},
  {year:"2015",make:"Ultima",model:"Evolution Coupe 1020",cls:"R"},
  {year:"2017",make:"Volkswagen",model:"#34 Andretti Rally Cross Beetle",cls:"S1"},
  {year:"1963",make:"Volkswagen",model:"Beetle",cls:"D"},
  {year:"1969",make:"Volkswagen",model:"Class 5/1600 Baja Bug",cls:"D"},
  {year:"1995",make:"Volkswagen",model:"Corrado VR6",cls:"C"},
  {year:"1983",make:"Volkswagen",model:"Golf GTI",cls:"D"},
  {year:"1992",make:"Volkswagen",model:"Golf Gti 16v Mk2",cls:"D"},
  {year:"2010",make:"Volkswagen",model:"Golf R",cls:"B"},
  {year:"2014",make:"Volkswagen",model:"Golf R",cls:"B"},
  {year:"2021",make:"Volkswagen",model:"Golf R",cls:"B"},
  {year:"2022",make:"Volkswagen",model:"Golf R",cls:"B"},
  {year:"1982",make:"Volkswagen",model:"Pickup LX",cls:"D"},
  {year:"1989",make:"Volkswagen",model:"Rallye Golf",cls:"C"},
  {year:"2011",make:"Volkswagen",model:"Scirocco R",cls:"B"},
  {year:"1963",make:"Volkswagen",model:"Type 2 De Luxe",cls:"D"},
  {year:"1983",make:"Volvo",model:"242 Turbo Evolution",cls:"C"},
  {year:"2022",make:"Wuling",model:"Hongguang Mini EV",cls:"D"},
  {year:"2013",make:"Wuling",model:"Sunshine S",cls:"D"},
  {year:"2013",make:"Wuling",model:"Sunshine S Forza Edition",cls:"S1"},
  {year:"2019",make:"Zenvo",model:"TSR-S",cls:"R"}
];